---
title: "Risk of Exclusion in Education due to the Covid-19 Outbreak in Ecuador"
author: "Max Aantjes"
date: "27/07/2020"
output:
  github_document:
    toc: true
    toc_depth: 3
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**The world is facing an unparalleled education crisis due to the impact of covid-19. In early April 2020, over 1.5 billion learners were affected by 174 country-wide school closures.^[4th of April, https://en.unesco.org/covid19/educationresponse] In late July, almost three months later, closures still affected over a billion learners.^[26th of July, ibid.] The Ecuadorian government has launched a variety of initiatives to ensure citizens' access to education during the lockdowns, but citizens have publicly started to question the effectiveness of this approach. An analysis of the data collected by a national multi-purpose household survey in 2019 does not only remove but strengthen such worries. It indicates that the government's approach, albeit understandable considering the resources available, will exacerbate existing inequalities.**

The government's efforts to ensure acccess to education have primarily focused on a rapid digitalisation of the education system. Country-wide school closures were announced in Ecuador on the 13th of March 2020.^[https://educacion.gob.ec/comunicado-oficial-suspension-de-las-actividades-academicas-para-los-estudiantes-para-precautelar-la-salud-de-la-comunidad-educativa/] On the 16th of March, digital classes commenced in the highlands and amazon regions, complemented by the launch of an online portal which serves as a repository of over 840 digital learning tools and a special website which hosts forums, videos, tutorials, homework and questionnaires for students in upper higher education.^[https://educacion.gob.ec/plan-educativo-covid-19-para-estudiantes-de-3-de-bachillerato/ and https://educacion.gob.ec/plan-educativo-covid-19-se-presento-el-16-de-marzo/] The same platforms were used in coastal regions, where schools started in May. To help families cope with these changes, the government released a digital guide with instructions on the set-up and use of technology required for online classes.^[https://coronavirusecuador.com/wp-content/uploads/2020/03/Aprendiendo_desde_casa.pdf] Teachers were similarly encouraged to engage with new and existing technology. On the 25th of March, all teachers were invited to register for an online course on the use of the digital resources made available by the government.^[https://educacion.gob.ec/el-ministerio-de-educacion-abre-el-curso-de-autoaprendizaje-mi-aula-en-linea/] In terms of coordination between teachers, educators working in coastal regions were encouraged to use Microsoft Teams  in anticipation of the new school year.^[https://educacion.gob.ec/docentes-de-regimen-costa-retomaran-actividades-mediante-teletrabajo/] 

Conversely, there have been important yet limited efforts to reach students and teachers with no access to internet. From the 23rd of March onwards, the delivery of educational content was expanded to TV and radio, with a daily one-hour educational broadcast on 160 different TV channels and a daily three-hour educational broadcast on national and local radio stations.^[https://educacion.gob.ec/la-educacion-a-traves-de-plataformas-digitales/] On the 30th of April 2020, the television broadcast was replaced by the A-prender la Tele show, a one-hour broadcast which linked entertainment with education and was jointly developed by the ministry of education, UNICEF Ecuador, IPANC (Instituto Iberoamericano del Patrimonio Natural y Cultural) and Edupasión. This programme targeted children between the ages of 5 to 8 and 9 to 14 years old.^[https://educacion.gob.ec/llega-a-aprender-la-tele-a-ala-pantalla-de-educa-contigo/] In terms of unconnected teachers, the government recommended any schools which did not have their own digital platforms to refer their students to the set of resources which were available through the website of the ministry of education.^[https://educacion.gob.ec/comunicado-oficial-el-ministerio-de-educacion-informa-a-la-comunidad-educativa-que-trabaja-de-manera-permanente-para-apoyar-en-el-nuevo-modelo-de-aprendizaje/] 

Despite the governments efforts, the focus on digital solutions threatens to exclude a large subset of the population due to at least three complimentary socioeconomic factors. 

Secondly, a substantial part of the population does not have access to internet. The survey results indicate that just below 60% of the school-going population have access to the internet at home, whilst less than 25% of the school-going population in rural areas have access to the internet at home. The results are reflected in figure 2. 


Firstly, a proportion of caretakers, children and teachers is not familiar with the use of electronic devices and digital services. 

Secondly






In 2016, an estimated 21.1% of 16 to 24 year-old Ecuadorians did not use computers at all.^[p.11 https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_Sociales/TIC/2016/170125.Presentacion_Tics_2016.pdf] Two years later, in 2018, only 62.1% of the rural population and 35.6% of the urban population were estimated to have used the internet at least once during that year.^[p. 12 https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_Sociales/TIC/2018/201812_Principales_resultados_TIC_Multiproposito.pdf] Complete or partial digital illitarcy reduces the efficiency or even possibility of receiving and delivering education.^[The Ecuadorian government considers a person digitally illiterate if they (i) do not have an activated cell phone, (ii) have not used a computer in the past 12 months and (iii) have not used the internet in the past 12 months. p. 32 https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_Sociales/TIC/2018/201812_Principales_resultados_TIC_Multiproposito.pdf, This seems to be a particularly limited definition of literacy, as using digital services effectively on a daily basis requires a certain knowledge on the functioning of key programmes and internet safety] Secondly, many Ecuadorians never had or no longer have access to the internet. Of the 5 to 17 year-old Ecuadorians who did manage to access the internet in 2018, 18.4% primarily did so through educational institutions whilst 4.8% primarily did so through the house of an acquaintance, which are both inaccessible during the lockdown.^[p. 16 https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_Sociales/TIC/2018/201812_Principales_resultados_TIC_Multiproposito.pdf] These learners are dependent on external internet sources because only 46.1% of urban households and 16.1% of rural households featured internet access.^[p. 6 https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_Sociales/TIC/2018/201812_Principales_resultados_TIC_Multiproposito.pdf]  Thirdly, working digital devices required for the use of both downloaded and online materials are not always available to children and young people in poor households. In 2018, the proportion of citizens aged 16 to 24 years old with an activated telephone was 71.1%.^[p. 19, https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_Sociales/TIC/2018/201812_Principales_resultados_TIC_Multiproposito.pdf] For smartphones, this proportion reduces to 63.2%.^[p. 25, https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_Sociales/TIC/2018/201812_Principales_resultados_TIC_Multiproposito.pdf] 

Another potential driver of exclusion is the worsening economic situation of poor households. School closures in March halted the delivery of school meals until the 29th of April, when a new 'school meal kits' distribution programme was rolled out in the highlands and Amazon regions.^[https://educacion.gob.ec/finaliza-plan-piloto-de-entrega-de-alimentacion-escolar/] Since figures from 2018 indicate that 50% of matriculated students received school meals on a daily basis, this gap in school meal delivery temporarily raised the expenditure of a large proportion of Ecuadorian households.^[calculations by author and available through appendix 1.1. Raw data collected by INEC through their 2018 TIC survey] The economic outlook in terms of the incomes of poor households is also bleak, with Ecuador's GDP expected to contract 6.5% in 2020 and extreme poverty in the whole Latin American region expected to grow from 11% to 13.5%.^[p. 16 https://repositorio.cepal.org/bitstream/handle/11362/45477/6/S2000285_en.pdf] These rising economic inequalities limit the effectivity of distance education. Young learners in households facing economic difficulties are less likely to allocate time to studying, particularly in times when compulsory school attendance is not verified by government officials. In a study conducted in Sierra Leone during the Ebola crisis, 43% of a sample of 216 children indicated they needed to work throughout the pandemic in order to support their families.^[file:///C:/Users/aantj/Downloads/2015_childrens_ebola_recovery_assessment_sierra_leone_en.pdf]  

It is a given that the systematic exclusion of learners with certain socioeconomic backgrounds fosters systematic inequalities in student performance. After all, marginalised learners miss out on the learning opportunities their peers have. Nevertheless, the effect of long-term exclusion can be more extreme. According to a recent literature review by the International Development Bank, young learners from low socioeconomic backgrounds lose the equivalent of 3 months of learning over their summer holidays, with a similar effect found during teacher strikes.^[https://blogs.iadb.org/ideas-matter/en/pandemic-and-inequality-how-much-human-capital-is-lost-when-schools-close/] Although efforts to continue engaging learners through radio and TV may lessen this effect, rising inequalities in student performance across different social groups seem inevitable. Bridging this gap will require the implementation of new non-digital learning programmes and the hiring of additional teachers for post-pandemic catch-up classes.^[An examplar case of non-digital initiatives is the Save the Children campaign in Uganda which distributed learning packs to 120,000 children. p. 9 https://resourcecentre.savethechildren.net/node/17871/pdf/save_our_education_0.pdf] In anticipation of these measures, this analysis aims to identify the Ecuadorian learners which have been marginalised by the school closure and the temporary digitalisation of education. With a greater understanding of the distribution of socio-economic factors which underpin marginalisation on regional, cantonal and parish level, the government can allocate additional funding to those areas that need it most. 
